env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  "no-console": "off",
  "import/extensions":
    [
        "error",
        "ignorePackages",
        { "js": "always" },
    ],
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
}
